version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  toxiproxy:
    build:
      context: ./docker/toxiproxy
    environment:
      PROXIES: "redis:26379:redis:6379"
    depends_on:
      - redis
    ports:
      - "26379:26379"
      - "8474:8474"


