# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'sidekiq', '5.0.5'
gem 'sidekiq-scheduler', '2.1.10'
gem 'redis-namespace', '1.6.0'
gem 'e2mmap'
gem 'thwait'
